name: Feature request
description: Suggest an improvement for telnom
title: "feat: "
labels:
  - enhancement
body:
  - type: textarea
    attributes:
      label: Description
      description: What would you like to add or improve?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Use case
      description: Why would this be useful?
    validations:
      required: true